/*
Flight Offers Price

Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization-262)** for more information on how to generate an access token.   Please also be aware that our test environment is based on a subset of the production, if you are not returning any results try with big cities/airports like LON (London) or NYC (New-York).

API version: 1.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"github.com/yenvanio/amadeus-go/amadeus/utils"
)

// checks if the GetPriceQuery type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &GetPriceQuery{}

// GetPriceQuery struct for GetPriceQuery
type GetPriceQuery struct {
	Data FlightOfferPricingIn `json:"data"`
}

// NewGetPriceQuery instantiates a new GetPriceQuery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPriceQuery(data FlightOfferPricingIn) *GetPriceQuery {
	this := GetPriceQuery{}
	this.Data = data
	return &this
}

// NewGetPriceQueryWithDefaults instantiates a new GetPriceQuery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPriceQueryWithDefaults() *GetPriceQuery {
	this := GetPriceQuery{}
	return &this
}

// GetData returns the Data field value
func (o *GetPriceQuery) GetData() FlightOfferPricingIn {
	if o == nil {
		var ret FlightOfferPricingIn
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetPriceQuery) GetDataOk() (*FlightOfferPricingIn, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetPriceQuery) SetData(v FlightOfferPricingIn) {
	o.Data = v
}

func (o GetPriceQuery) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetPriceQuery) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableGetPriceQuery struct {
	value *GetPriceQuery
	isSet bool
}

func (v NullableGetPriceQuery) Get() *GetPriceQuery {
	return v.value
}

func (v *NullableGetPriceQuery) Set(val *GetPriceQuery) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPriceQuery) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPriceQuery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPriceQuery(val *GetPriceQuery) *NullableGetPriceQuery {
	return &NullableGetPriceQuery{value: val, isSet: true}
}

func (v NullableGetPriceQuery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPriceQuery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


