/*
Flight Offers Price

Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization-262)** for more information on how to generate an access token.   Please also be aware that our test environment is based on a subset of the production, if you are not returning any results try with big cities/airports like LON (London) or NYC (New-York).

API version: 1.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"github.com/yenvanio/amadeus-go/amadeus"
)

// checks if the Traveler type satisfies the MappedNullable interface at compile time
var _ amadeus.MappedNullable = &Traveler{}

// Traveler the traveler of the trip
type Traveler struct {
	// item identifier
	Id *string `json:"id,omitempty"`
	// The date of birth in ISO 8601 format (yyyy-mm-dd)
	DateOfBirth *string       `json:"dateOfBirth,omitempty"`
	Gender *StakeholderGender `json:"gender,omitempty"`
	Name *Name                `json:"name,omitempty"`
	// Advanced Passenger Information - regulatory identity documents - SSR DOCS & DOCO elements
	Documents []IdentityDocument       `json:"documents,omitempty"`
	EmergencyContact *EmergencyContact `json:"emergencyContact,omitempty"`
	// list of loyalty program followed by the traveler
	LoyaltyPrograms []LoyaltyProgram `json:"loyaltyPrograms,omitempty"`
	// list of element that allow a discount.
	DiscountEligibility []Discount `json:"discountEligibility,omitempty"`
	Contact *Contact               `json:"contact,omitempty"`
}

// NewTraveler instantiates a new Traveler object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTraveler() *Traveler {
	this := Traveler{}
	return &this
}

// NewTravelerWithDefaults instantiates a new Traveler object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTravelerWithDefaults() *Traveler {
	this := Traveler{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Traveler) GetId() string {
	if o == nil || amadeus.IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Traveler) GetIdOk() (*string, bool) {
	if o == nil || amadeus.IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Traveler) HasId() bool {
	if o != nil && !amadeus.IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Traveler) SetId(v string) {
	o.Id = &v
}

// GetDateOfBirth returns the DateOfBirth field value if set, zero value otherwise.
func (o *Traveler) GetDateOfBirth() string {
	if o == nil || amadeus.IsNil(o.DateOfBirth) {
		var ret string
		return ret
	}
	return *o.DateOfBirth
}

// GetDateOfBirthOk returns a tuple with the DateOfBirth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Traveler) GetDateOfBirthOk() (*string, bool) {
	if o == nil || amadeus.IsNil(o.DateOfBirth) {
		return nil, false
	}
	return o.DateOfBirth, true
}

// HasDateOfBirth returns a boolean if a field has been set.
func (o *Traveler) HasDateOfBirth() bool {
	if o != nil && !amadeus.IsNil(o.DateOfBirth) {
		return true
	}

	return false
}

// SetDateOfBirth gets a reference to the given string and assigns it to the DateOfBirth field.
func (o *Traveler) SetDateOfBirth(v string) {
	o.DateOfBirth = &v
}

// GetGender returns the Gender field value if set, zero value otherwise.
func (o *Traveler) GetGender() StakeholderGender {
	if o == nil || amadeus.IsNil(o.Gender) {
		var ret StakeholderGender
		return ret
	}
	return *o.Gender
}

// GetGenderOk returns a tuple with the Gender field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Traveler) GetGenderOk() (*StakeholderGender, bool) {
	if o == nil || amadeus.IsNil(o.Gender) {
		return nil, false
	}
	return o.Gender, true
}

// HasGender returns a boolean if a field has been set.
func (o *Traveler) HasGender() bool {
	if o != nil && !amadeus.IsNil(o.Gender) {
		return true
	}

	return false
}

// SetGender gets a reference to the given StakeholderGender and assigns it to the Gender field.
func (o *Traveler) SetGender(v StakeholderGender) {
	o.Gender = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Traveler) GetName() Name {
	if o == nil || amadeus.IsNil(o.Name) {
		var ret Name
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Traveler) GetNameOk() (*Name, bool) {
	if o == nil || amadeus.IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Traveler) HasName() bool {
	if o != nil && !amadeus.IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given Name and assigns it to the Name field.
func (o *Traveler) SetName(v Name) {
	o.Name = &v
}

// GetDocuments returns the Documents field value if set, zero value otherwise.
func (o *Traveler) GetDocuments() []IdentityDocument {
	if o == nil || amadeus.IsNil(o.Documents) {
		var ret []IdentityDocument
		return ret
	}
	return o.Documents
}

// GetDocumentsOk returns a tuple with the Documents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Traveler) GetDocumentsOk() ([]IdentityDocument, bool) {
	if o == nil || amadeus.IsNil(o.Documents) {
		return nil, false
	}
	return o.Documents, true
}

// HasDocuments returns a boolean if a field has been set.
func (o *Traveler) HasDocuments() bool {
	if o != nil && !amadeus.IsNil(o.Documents) {
		return true
	}

	return false
}

// SetDocuments gets a reference to the given []IdentityDocument and assigns it to the Documents field.
func (o *Traveler) SetDocuments(v []IdentityDocument) {
	o.Documents = v
}

// GetEmergencyContact returns the EmergencyContact field value if set, zero value otherwise.
func (o *Traveler) GetEmergencyContact() EmergencyContact {
	if o == nil || amadeus.IsNil(o.EmergencyContact) {
		var ret EmergencyContact
		return ret
	}
	return *o.EmergencyContact
}

// GetEmergencyContactOk returns a tuple with the EmergencyContact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Traveler) GetEmergencyContactOk() (*EmergencyContact, bool) {
	if o == nil || amadeus.IsNil(o.EmergencyContact) {
		return nil, false
	}
	return o.EmergencyContact, true
}

// HasEmergencyContact returns a boolean if a field has been set.
func (o *Traveler) HasEmergencyContact() bool {
	if o != nil && !amadeus.IsNil(o.EmergencyContact) {
		return true
	}

	return false
}

// SetEmergencyContact gets a reference to the given EmergencyContact and assigns it to the EmergencyContact field.
func (o *Traveler) SetEmergencyContact(v EmergencyContact) {
	o.EmergencyContact = &v
}

// GetLoyaltyPrograms returns the LoyaltyPrograms field value if set, zero value otherwise.
func (o *Traveler) GetLoyaltyPrograms() []LoyaltyProgram {
	if o == nil || amadeus.IsNil(o.LoyaltyPrograms) {
		var ret []LoyaltyProgram
		return ret
	}
	return o.LoyaltyPrograms
}

// GetLoyaltyProgramsOk returns a tuple with the LoyaltyPrograms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Traveler) GetLoyaltyProgramsOk() ([]LoyaltyProgram, bool) {
	if o == nil || amadeus.IsNil(o.LoyaltyPrograms) {
		return nil, false
	}
	return o.LoyaltyPrograms, true
}

// HasLoyaltyPrograms returns a boolean if a field has been set.
func (o *Traveler) HasLoyaltyPrograms() bool {
	if o != nil && !amadeus.IsNil(o.LoyaltyPrograms) {
		return true
	}

	return false
}

// SetLoyaltyPrograms gets a reference to the given []LoyaltyProgram and assigns it to the LoyaltyPrograms field.
func (o *Traveler) SetLoyaltyPrograms(v []LoyaltyProgram) {
	o.LoyaltyPrograms = v
}

// GetDiscountEligibility returns the DiscountEligibility field value if set, zero value otherwise.
func (o *Traveler) GetDiscountEligibility() []Discount {
	if o == nil || amadeus.IsNil(o.DiscountEligibility) {
		var ret []Discount
		return ret
	}
	return o.DiscountEligibility
}

// GetDiscountEligibilityOk returns a tuple with the DiscountEligibility field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Traveler) GetDiscountEligibilityOk() ([]Discount, bool) {
	if o == nil || amadeus.IsNil(o.DiscountEligibility) {
		return nil, false
	}
	return o.DiscountEligibility, true
}

// HasDiscountEligibility returns a boolean if a field has been set.
func (o *Traveler) HasDiscountEligibility() bool {
	if o != nil && !amadeus.IsNil(o.DiscountEligibility) {
		return true
	}

	return false
}

// SetDiscountEligibility gets a reference to the given []Discount and assigns it to the DiscountEligibility field.
func (o *Traveler) SetDiscountEligibility(v []Discount) {
	o.DiscountEligibility = v
}

// GetContact returns the Contact field value if set, zero value otherwise.
func (o *Traveler) GetContact() Contact {
	if o == nil || amadeus.IsNil(o.Contact) {
		var ret Contact
		return ret
	}
	return *o.Contact
}

// GetContactOk returns a tuple with the Contact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Traveler) GetContactOk() (*Contact, bool) {
	if o == nil || amadeus.IsNil(o.Contact) {
		return nil, false
	}
	return o.Contact, true
}

// HasContact returns a boolean if a field has been set.
func (o *Traveler) HasContact() bool {
	if o != nil && !amadeus.IsNil(o.Contact) {
		return true
	}

	return false
}

// SetContact gets a reference to the given Contact and assigns it to the Contact field.
func (o *Traveler) SetContact(v Contact) {
	o.Contact = &v
}

func (o Traveler) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Traveler) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !amadeus.IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !amadeus.IsNil(o.DateOfBirth) {
		toSerialize["dateOfBirth"] = o.DateOfBirth
	}
	if !amadeus.IsNil(o.Gender) {
		toSerialize["gender"] = o.Gender
	}
	if !amadeus.IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !amadeus.IsNil(o.Documents) {
		toSerialize["documents"] = o.Documents
	}
	if !amadeus.IsNil(o.EmergencyContact) {
		toSerialize["emergencyContact"] = o.EmergencyContact
	}
	if !amadeus.IsNil(o.LoyaltyPrograms) {
		toSerialize["loyaltyPrograms"] = o.LoyaltyPrograms
	}
	if !amadeus.IsNil(o.DiscountEligibility) {
		toSerialize["discountEligibility"] = o.DiscountEligibility
	}
	if !amadeus.IsNil(o.Contact) {
		toSerialize["contact"] = o.Contact
	}
	return toSerialize, nil
}

type NullableTraveler struct {
	value *Traveler
	isSet bool
}

func (v NullableTraveler) Get() *Traveler {
	return v.value
}

func (v *NullableTraveler) Set(val *Traveler) {
	v.value = val
	v.isSet = true
}

func (v NullableTraveler) IsSet() bool {
	return v.isSet
}

func (v *NullableTraveler) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTraveler(val *Traveler) *NullableTraveler {
	return &NullableTraveler{value: val, isSet: true}
}

func (v NullableTraveler) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTraveler) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


