/*
Flight Offers Search

 Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization-262)** for more information on how to generate an access token.   Please also be aware that our test environment is based on a subset of the production, if you are not returning any results try with big cities/airports like LON (London) or NYC (New-York).

API version: 2.9.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"github.com/GIT_USER_ID/GIT_REPO_ID/api"
)

// checks if the Success type satisfies the MappedNullable interface at compile time
var _ api.MappedNullable = &Success{}

// Success struct for Success
type Success struct {
	Warnings []Issue           `json:"warnings,omitempty"`
	Meta *CollectionMetaLink   `json:"meta,omitempty"`
	Data []FlightOffer         `json:"data"`
	Dictionaries *Dictionaries `json:"dictionaries,omitempty"`
}

// NewSuccess instantiates a new Success object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSuccess(data []FlightOffer) *Success {
	this := Success{}
	this.Data = data
	return &this
}

// NewSuccessWithDefaults instantiates a new Success object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSuccessWithDefaults() *Success {
	this := Success{}
	return &this
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *Success) GetWarnings() []Issue {
	if o == nil || api.IsNil(o.Warnings) {
		var ret []Issue
		return ret
	}
	return o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Success) GetWarningsOk() ([]Issue, bool) {
	if o == nil || api.IsNil(o.Warnings) {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *Success) HasWarnings() bool {
	if o != nil && !api.IsNil(o.Warnings) {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []Issue and assigns it to the Warnings field.
func (o *Success) SetWarnings(v []Issue) {
	o.Warnings = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *Success) GetMeta() CollectionMetaLink {
	if o == nil || api.IsNil(o.Meta) {
		var ret CollectionMetaLink
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Success) GetMetaOk() (*CollectionMetaLink, bool) {
	if o == nil || api.IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *Success) HasMeta() bool {
	if o != nil && !api.IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given CollectionMetaLink and assigns it to the Meta field.
func (o *Success) SetMeta(v CollectionMetaLink) {
	o.Meta = &v
}

// GetData returns the Data field value
func (o *Success) GetData() []FlightOffer {
	if o == nil {
		var ret []FlightOffer
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *Success) GetDataOk() ([]FlightOffer, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *Success) SetData(v []FlightOffer) {
	o.Data = v
}

// GetDictionaries returns the Dictionaries field value if set, zero value otherwise.
func (o *Success) GetDictionaries() Dictionaries {
	if o == nil || api.IsNil(o.Dictionaries) {
		var ret Dictionaries
		return ret
	}
	return *o.Dictionaries
}

// GetDictionariesOk returns a tuple with the Dictionaries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Success) GetDictionariesOk() (*Dictionaries, bool) {
	if o == nil || api.IsNil(o.Dictionaries) {
		return nil, false
	}
	return o.Dictionaries, true
}

// HasDictionaries returns a boolean if a field has been set.
func (o *Success) HasDictionaries() bool {
	if o != nil && !api.IsNil(o.Dictionaries) {
		return true
	}

	return false
}

// SetDictionaries gets a reference to the given Dictionaries and assigns it to the Dictionaries field.
func (o *Success) SetDictionaries(v Dictionaries) {
	o.Dictionaries = &v
}

func (o Success) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Success) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !api.IsNil(o.Warnings) {
		toSerialize["warnings"] = o.Warnings
	}
	if !api.IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	toSerialize["data"] = o.Data
	if !api.IsNil(o.Dictionaries) {
		toSerialize["dictionaries"] = o.Dictionaries
	}
	return toSerialize, nil
}

type NullableSuccess struct {
	value *Success
	isSet bool
}

func (v NullableSuccess) Get() *Success {
	return v.value
}

func (v *NullableSuccess) Set(val *Success) {
	v.value = val
	v.isSet = true
}

func (v NullableSuccess) IsSet() bool {
	return v.isSet
}

func (v *NullableSuccess) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuccess(val *Success) *NullableSuccess {
	return &NullableSuccess{value: val, isSet: true}
}

func (v NullableSuccess) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuccess) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


