/*
Flight Offers Price

Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization-262)** for more information on how to generate an access token.   Please also be aware that our test environment is based on a subset of the production, if you are not returning any results try with big cities/airports like LON (London) or NYC (New-York).

API version: 1.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"github.com/GIT_USER_ID/GIT_REPO_ID/api"
)

// checks if the IncludedResourcesMap type satisfies the MappedNullable interface at compile time
var _ api.MappedNullable = &IncludedResourcesMap{}

// IncludedResourcesMap struct for IncludedResourcesMap
type IncludedResourcesMap struct {
	// Map of fee applied by credit card brand
	CreditCardFees map[string]interface{} `json:"credit-card-fees,omitempty"`
	// Map of fee applied by bag option
	Bags map[string]interface{} `json:"bags,omitempty"`
	// Map of fee applied by service
	OtherServices map[string]interface{} `json:"other-services,omitempty"`
	// Map of fare rules applied by farebasis
	DetailedFareRules map[string]interface{} `json:"detailed-fare-rules,omitempty"`
}

// NewIncludedResourcesMap instantiates a new IncludedResourcesMap object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIncludedResourcesMap() *IncludedResourcesMap {
	this := IncludedResourcesMap{}
	return &this
}

// NewIncludedResourcesMapWithDefaults instantiates a new IncludedResourcesMap object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIncludedResourcesMapWithDefaults() *IncludedResourcesMap {
	this := IncludedResourcesMap{}
	return &this
}

// GetCreditCardFees returns the CreditCardFees field value if set, zero value otherwise.
func (o *IncludedResourcesMap) GetCreditCardFees() map[string]interface{} {
	if o == nil || api.IsNil(o.CreditCardFees) {
		var ret map[string]interface{}
		return ret
	}
	return o.CreditCardFees
}

// GetCreditCardFeesOk returns a tuple with the CreditCardFees field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncludedResourcesMap) GetCreditCardFeesOk() (map[string]interface{}, bool) {
	if o == nil || api.IsNil(o.CreditCardFees) {
		return map[string]interface{}{}, false
	}
	return o.CreditCardFees, true
}

// HasCreditCardFees returns a boolean if a field has been set.
func (o *IncludedResourcesMap) HasCreditCardFees() bool {
	if o != nil && !api.IsNil(o.CreditCardFees) {
		return true
	}

	return false
}

// SetCreditCardFees gets a reference to the given map[string]interface{} and assigns it to the CreditCardFees field.
func (o *IncludedResourcesMap) SetCreditCardFees(v map[string]interface{}) {
	o.CreditCardFees = v
}

// GetBags returns the Bags field value if set, zero value otherwise.
func (o *IncludedResourcesMap) GetBags() map[string]interface{} {
	if o == nil || api.IsNil(o.Bags) {
		var ret map[string]interface{}
		return ret
	}
	return o.Bags
}

// GetBagsOk returns a tuple with the Bags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncludedResourcesMap) GetBagsOk() (map[string]interface{}, bool) {
	if o == nil || api.IsNil(o.Bags) {
		return map[string]interface{}{}, false
	}
	return o.Bags, true
}

// HasBags returns a boolean if a field has been set.
func (o *IncludedResourcesMap) HasBags() bool {
	if o != nil && !api.IsNil(o.Bags) {
		return true
	}

	return false
}

// SetBags gets a reference to the given map[string]interface{} and assigns it to the Bags field.
func (o *IncludedResourcesMap) SetBags(v map[string]interface{}) {
	o.Bags = v
}

// GetOtherServices returns the OtherServices field value if set, zero value otherwise.
func (o *IncludedResourcesMap) GetOtherServices() map[string]interface{} {
	if o == nil || api.IsNil(o.OtherServices) {
		var ret map[string]interface{}
		return ret
	}
	return o.OtherServices
}

// GetOtherServicesOk returns a tuple with the OtherServices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncludedResourcesMap) GetOtherServicesOk() (map[string]interface{}, bool) {
	if o == nil || api.IsNil(o.OtherServices) {
		return map[string]interface{}{}, false
	}
	return o.OtherServices, true
}

// HasOtherServices returns a boolean if a field has been set.
func (o *IncludedResourcesMap) HasOtherServices() bool {
	if o != nil && !api.IsNil(o.OtherServices) {
		return true
	}

	return false
}

// SetOtherServices gets a reference to the given map[string]interface{} and assigns it to the OtherServices field.
func (o *IncludedResourcesMap) SetOtherServices(v map[string]interface{}) {
	o.OtherServices = v
}

// GetDetailedFareRules returns the DetailedFareRules field value if set, zero value otherwise.
func (o *IncludedResourcesMap) GetDetailedFareRules() map[string]interface{} {
	if o == nil || api.IsNil(o.DetailedFareRules) {
		var ret map[string]interface{}
		return ret
	}
	return o.DetailedFareRules
}

// GetDetailedFareRulesOk returns a tuple with the DetailedFareRules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncludedResourcesMap) GetDetailedFareRulesOk() (map[string]interface{}, bool) {
	if o == nil || api.IsNil(o.DetailedFareRules) {
		return map[string]interface{}{}, false
	}
	return o.DetailedFareRules, true
}

// HasDetailedFareRules returns a boolean if a field has been set.
func (o *IncludedResourcesMap) HasDetailedFareRules() bool {
	if o != nil && !api.IsNil(o.DetailedFareRules) {
		return true
	}

	return false
}

// SetDetailedFareRules gets a reference to the given map[string]interface{} and assigns it to the DetailedFareRules field.
func (o *IncludedResourcesMap) SetDetailedFareRules(v map[string]interface{}) {
	o.DetailedFareRules = v
}

func (o IncludedResourcesMap) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IncludedResourcesMap) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !api.IsNil(o.CreditCardFees) {
		toSerialize["credit-card-fees"] = o.CreditCardFees
	}
	if !api.IsNil(o.Bags) {
		toSerialize["bags"] = o.Bags
	}
	if !api.IsNil(o.OtherServices) {
		toSerialize["other-services"] = o.OtherServices
	}
	if !api.IsNil(o.DetailedFareRules) {
		toSerialize["detailed-fare-rules"] = o.DetailedFareRules
	}
	return toSerialize, nil
}

type NullableIncludedResourcesMap struct {
	value *IncludedResourcesMap
	isSet bool
}

func (v NullableIncludedResourcesMap) Get() *IncludedResourcesMap {
	return v.value
}

func (v *NullableIncludedResourcesMap) Set(val *IncludedResourcesMap) {
	v.value = val
	v.isSet = true
}

func (v NullableIncludedResourcesMap) IsSet() bool {
	return v.isSet
}

func (v *NullableIncludedResourcesMap) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIncludedResourcesMap(val *IncludedResourcesMap) *NullableIncludedResourcesMap {
	return &NullableIncludedResourcesMap{value: val, isSet: true}
}

func (v NullableIncludedResourcesMap) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIncludedResourcesMap) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


