/*
Flight Offers Price

Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization-262)** for more information on how to generate an access token.   Please also be aware that our test environment is based on a subset of the production, if you are not returning any results try with big cities/airports like LON (London) or NYC (New-York).

API version: 1.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"github.com/GIT_USER_ID/GIT_REPO_ID"
	"github.com/GIT_USER_ID/GIT_REPO_ID/api"
)

// checks if the FlightOfferPricingOut type satisfies the MappedNullable interface at compile time
var _ api.MappedNullable = &FlightOfferPricingOut{}

// FlightOfferPricingOut priced flight Offers and conditions
type FlightOfferPricingOut struct {
	// the resource name
	Type string `json:"type"`
	// list of flight offer to price
	FlightOffers []openapi.FlightOffer       `json:"flightOffers"`
	BookingRequirements *BookingRequirements `json:"bookingRequirements,omitempty"`
}

// NewFlightOfferPricingOut instantiates a new FlightOfferPricingOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFlightOfferPricingOut(type_ string, flightOffers []openapi.FlightOffer) *FlightOfferPricingOut {
	this := FlightOfferPricingOut{}
	this.Type = type_
	this.FlightOffers = flightOffers
	return &this
}

// NewFlightOfferPricingOutWithDefaults instantiates a new FlightOfferPricingOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFlightOfferPricingOutWithDefaults() *FlightOfferPricingOut {
	this := FlightOfferPricingOut{}
	return &this
}

// GetType returns the Type field value
func (o *FlightOfferPricingOut) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *FlightOfferPricingOut) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *FlightOfferPricingOut) SetType(v string) {
	o.Type = v
}

// GetFlightOffers returns the FlightOffers field value
func (o *FlightOfferPricingOut) GetFlightOffers() []openapi.FlightOffer {
	if o == nil {
		var ret []openapi.FlightOffer
		return ret
	}

	return o.FlightOffers
}

// GetFlightOffersOk returns a tuple with the FlightOffers field value
// and a boolean to check if the value has been set.
func (o *FlightOfferPricingOut) GetFlightOffersOk() ([]openapi.FlightOffer, bool) {
	if o == nil {
		return nil, false
	}
	return o.FlightOffers, true
}

// SetFlightOffers sets field value
func (o *FlightOfferPricingOut) SetFlightOffers(v []openapi.FlightOffer) {
	o.FlightOffers = v
}

// GetBookingRequirements returns the BookingRequirements field value if set, zero value otherwise.
func (o *FlightOfferPricingOut) GetBookingRequirements() BookingRequirements {
	if o == nil || api.IsNil(o.BookingRequirements) {
		var ret BookingRequirements
		return ret
	}
	return *o.BookingRequirements
}

// GetBookingRequirementsOk returns a tuple with the BookingRequirements field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlightOfferPricingOut) GetBookingRequirementsOk() (*BookingRequirements, bool) {
	if o == nil || api.IsNil(o.BookingRequirements) {
		return nil, false
	}
	return o.BookingRequirements, true
}

// HasBookingRequirements returns a boolean if a field has been set.
func (o *FlightOfferPricingOut) HasBookingRequirements() bool {
	if o != nil && !api.IsNil(o.BookingRequirements) {
		return true
	}

	return false
}

// SetBookingRequirements gets a reference to the given BookingRequirements and assigns it to the BookingRequirements field.
func (o *FlightOfferPricingOut) SetBookingRequirements(v BookingRequirements) {
	o.BookingRequirements = &v
}

func (o FlightOfferPricingOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FlightOfferPricingOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["flightOffers"] = o.FlightOffers
	if !api.IsNil(o.BookingRequirements) {
		toSerialize["bookingRequirements"] = o.BookingRequirements
	}
	return toSerialize, nil
}

type NullableFlightOfferPricingOut struct {
	value *FlightOfferPricingOut
	isSet bool
}

func (v NullableFlightOfferPricingOut) Get() *FlightOfferPricingOut {
	return v.value
}

func (v *NullableFlightOfferPricingOut) Set(val *FlightOfferPricingOut) {
	v.value = val
	v.isSet = true
}

func (v NullableFlightOfferPricingOut) IsSet() bool {
	return v.isSet
}

func (v *NullableFlightOfferPricingOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFlightOfferPricingOut(val *FlightOfferPricingOut) *NullableFlightOfferPricingOut {
	return &NullableFlightOfferPricingOut{value: val, isSet: true}
}

func (v NullableFlightOfferPricingOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFlightOfferPricingOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


